name: Style Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  style:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "requirements*.txt"
    
    - name: Install just
      uses: extractions/setup-just@v2
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: just install
    
    - name: Check code formatting and linting
      run: |
        uv run ruff check src/ tests/
        uv run ruff format --check src/ tests/